4500000: УСЛУГИ СТРОИТЕЛЬНЫЕ И ОБЪЕКТЫ СТРОИТЕЛЬСТВА 
0141372: Работы земляные (рытье котлованов и траншей, засыпка котлованов и траншей)
1120111: Строительство буровых вышек
1120112: Ремонт буровых вышек
1120113: Демонтаж буровых вышек
5020550: Ремонт и замена стекол
5269220: Услуги по ремонту нитроцеллюлозных и полиэфирных покрытий с полным удалением старого лакокрасочного покрытия и отделкой заново
5269230: Частичный ремонт нитроцеллюлозных и полиэфирных покрытий с удалением старого покрытия и отделкой дефектного участка
9310000: УСЛУГИ ЖИЛИЩНО - КОММУНАЛЬНЫЕ
9314101: Комплексный ремонт жилищ (квартир, домов)
9314102: Частичный ремонт жилищ (квартир, домов)
9314105: Ремонт крыш и кровель
9314106: Ремонт подвальных помещений, фундаментов и погребов
9314107: Ремонт полов всех видов
9314109: Ремонт и замена оконных и дверных коробок, переплетов, полофорточек, замена скобяных изделий
9314110: Ремонт внутренней электропроводки и смена электроосветительной аппаратуры
9314120: Ремонт внутренних систем водяного отопления в индивидуальных жилых домах
9314140: Перекладка и ремонт печей, дымоходов, газоходов
9314150: Ремонт садовых домиков
9314160: Ремонт хозяйственных построек
9314170: Ремонт колодцев
9314180: Ремонт индивидуальных гаражей
9314190: Ремонт оград и заборов (кроме металлических)
9314250: Строительство жилищ (квартир)
9314261: Строительство индивидуальных домов
9314262: Возведение хозяйственных построек (сараев, погребов, навесов, летних кухонь и построек прочих)
9314263: Сборка деревянных домов заводского изготовления
9314264: Изготовление, разборка и сборка бревенчатых и брусчатых срубов
9314265: Изготовление и строительство садовых домиков
9314266: Обшивка наружных стен домов шпунтованной доской
9314268: Облицовка наружных стен кирпичом и декоративной бетонной или железобетонной плиткой
9314271: Подшивка потолков древесно - волокнистой плитой и материалами прочими
9314272: Установка декоративных решеток и панелей
9314273: Оформление лоджий и балконов ????
9314274: Устройство полов всех видов
9314275: Штукатурка стен, потолков, пилонов, колонн, откосов по бетонной, кирпичной и деревянной поверхности
9314276: Обивка и утепление дверей, вставка глазков и скобяных изделий, укрепление дверных коробок
9314277: Облицовка внутренних стен древесно - волокнистыми и гипсокартонными плитами и материалами прочими
9314278: Альфрейные работы (декоративная отделка поверхностей) ???
9314279: Изготовление и монтаж лепных элементов, украшение интерьера жилищ (квартир, домов)
9314281: Кладка печей, очагов, дымоходов и газоходов
9314282: Строительство индивидуальных гаражей
9314283: Пристройка веранды и теплых туалетов
9314284: Изготовление и сборка теплых туалетов ???
9314286: Строительство индивидуальных бань
9314287: Устройство индивидуального водяного отопления
9314288: Устройство индивидуального водопровода
9314289: Строительство колодцев
9314291: Бурение и оборудование скважин
9314292: Монтаж внутренних электропроводок и электроосветительной арматуры
9314293: Изоляционные работы
9314294: Облицовочные работы
9314295: Стекольные работы
9314296: Обойные работы
9314297: Малярные работы
9314298: Оформление интерьера жилых домов и вспомогательных помещений    ????
9314101: Комплексный ремонт жилищ (квартир, домов)
9314105: Ремонт крыш и кровель
1120111: Строительство буровых вышек
1120112: Ремонт буровых вышек
1120113: Демонтаж буровых вышек
1120121: Цементирование насосных скважин
1120122: Забивка и ликвидация скважин
112013: Услуги, связанные со строительством и эксплуатацией скважин, прочие
014133: Строительство ограждений для культурных пастбищ
0141361: Строительство закрытых дренажей
112011: Строительство, ремонт и демонтаж буровых вышек
112013: Услуги, связанные со строительством и эксплуатацией скважин, прочие
5110320: Услуги по торговле строительными материалами
5110321: Услуги по торговле элементами, узлами и блоками строительных конструкций
5110324: Услуги по торговле связующими строительных материалов и компонентами для них
5110325: Услуги по торговле строительными изделиями и материалами прочими
5143000: УСЛУГИ ПО ОПТОВОЙ ТОРГОВЛЕ СТРОИТЕЛЬНЫМИ МАТЕРИАЛАМИ, СКОБЯНЫМИ ИЗДЕЛИЯМИ, ВОДОПРОВОДНЫМ И ОТОПИТЕЛЬНЫМ ОБОРУДОВАНИЕМ И ВСПОМОГАТЕЛЬНЫМИ МАТЕРИАЛАМИ
5143030: Услуги по оптовой торговле строительными материалами, арматурой, оборудованием и листовым стеклом [5143210] - [5143290]
5143210: Услуги по оптовой торговле строительной арматурой и оборудованием
5143290: Услуги по оптовой торговле видами строительных материалов прочими
5150030: Услуги по оптовой торговле машинами и оборудованием для промышленного и гражданского строительства [5150300] - [5150310]
5150300: Услуги по оптовой торговле машинами и оборудованием для промышленного строительства
5150310: Услуги по оптовой торговле машинами и оборудованием для гражданского строительства
6220064: Услуги воздушного транспорта для выполнения строительно-монтажных и погрузочно-разгрузочных работ
7122000: УСЛУГИ ПО ЛИЗИНГУ ИЛИ АРЕНДЕ СТРОИТЕЛЬНЫХ МАШИН И ОБОРУДОВАНИЯ БЕЗ ОПЕРАТОРА
7421074: Услуги по геологическим, геофизическим изысканиям и видам научных изысканий, связанных со строительством, прочим
7513034: Административные услуги, связанные со строительной индустрией
7421026: Инженерные услуги, оказываемые в процессе строительства зданий и монтажа оборудования
7421029: Инженерные услуги в области проектно - строительных работ прочие
7421050: Комплексные инженерные услуги по строительству
7421054: Комплексные инженерные услуги для проектов гражданского строительства со сдачей "под ключ"
9314000: УСЛУГИ ПО РЕМОНТУ ЖИЛИЩ (КВАРТИР, ДОМОВ) И СТРОИТЕЛЬСТВУ ИНДИВИДУАЛЬНОГО ЖИЛЬЯ
9314020: Услуги по строительству индивидуального жилья по заказу граждан [9314250] - [9314298]
9314250: Строительство жилищ (квартир)
9314260: Строительство индивидуальных домов и построек приусадебных
9314261: Строительство индивидуальных домов
9314265: Изготовление и строительство садовых домиков
9314282: Строительство индивидуальных гаражей
9314286: Строительство индивидуальных бань
9314289: Строительство колодцев
9319011: Услуги, предоставляемые при ремонте и строительстве жилья, прочие [9319100] - [9319108]
9319100: Услуги, предоставляемые населению при ремонте и строительстве жилищ (квартир), прочие
9319101: Изготовление столярных строительных деталей и изделий
9319102: Изготовление железобетонных строительных изделий и деталей
9319105: Разработка проектно - сметной документации на строительство реконструкцию жилых и нежилых строений, благоустройство индивидуальных домов и приусадебных участков
9319106: Консультации специалиста при выполнении заказчиком ремонта, строительных работ своими силами по принципу "Сделай сам"
5110301: Услуги по торговле необработанной древесиной
5110302: Услуги по торговле обработанной древесиной
5110310: Услуги по торговле полуфабрикатами из древесины
5110321: Услуги по торговле элементами, узлами и блоками строительных конструкций
5110322: Услуги по торговле листовым стеклом
5110323: Услуги по торговле газовым, водопроводным и отопительным оборудованием
5110324: Услуги по торговле связующими строительных материалов и компонентами для них
5110325: Услуги по торговле строительными изделиями и материалами прочими
5143210: Услуги по оптовой торговле строительной арматурой и оборудованием
5143220: Услуги по оптовой торговле листовым стеклом
5143290: Услуги по оптовой торговле видами строительных материалов прочими
5150300: Услуги по оптовой торговле машинами и оборудованием для промышленного строительства
5150310: Услуги по оптовой торговле машинами и оборудованием для гражданского строительства
9314250: Строительство жилищ (квартир)
9314261: Строительство индивидуальных домов
9314262: Возведение хозяйственных построек (сараев, погребов, навесов, летних кухонь и построек прочих)
9314263: Сборка деревянных домов заводского изготовления
9314264: Изготовление, разборка и сборка бревенчатых и брусчатых срубов
9314265: Изготовление и строительство садовых домиков
9314266: Обшивка наружных стен домов шпунтованной доской
9314267: Украшение фасадов домов различными элементами из дерева
9314268: Облицовка наружных стен кирпичом и декоративной бетонной или железобетонной плиткой
9314269: Заполнение установленных коробок в шкафах и антресолях
9314271: Подшивка потолков древесно - волокнистой плитой и материалами прочими
9314272: Установка декоративных решеток и панелей
9314273: Оформление лоджий и балконов
9314274: Устройство полов всех видов
9314275: Штукатурка стен, потолков, пилонов, колонн, откосов по бетонной, кирпичной и деревянной поверхности
9314276: Обивка и утепление дверей, вставка глазков и скобяных изделий, укрепление дверных коробок
9314277: Облицовка внутренних стен древесно - волокнистыми и гипсокартонными плитами и материалами прочими
9314278: Альфрейные работы (декоративная отделка поверхностей)
9314279: Изготовление и монтаж лепных элементов, украшение интерьера жилищ (квартир, домов)
9314281: Кладка печей, очагов, дымоходов и газоходов
9314282: Строительство индивидуальных гаражей
9314283: Пристройка веранды и теплых туалетов
9314284: Изготовление и сборка теплых туалетов
9314285: Устройство оград и заборов (кроме металлических)
9314286: Строительство индивидуальных бань
9314287: Устройство индивидуального водяного отопления
9314288: Устройство индивидуального водопровода
9314289: Строительство колодцев
9314291: Бурение и оборудование скважин
9314292: Монтаж внутренних электропроводок и электроосветительной арматуры
9314293: Изоляционные работы
9314294: Облицовочные работы
9314295: Стекольные работы
9314296: Обойные работы
9314297: Малярные работы
9314298: Оформление интерьера жилых домов и вспомогательных помещений
9319101: Изготовление столярных строительных деталей и изделий
9319102: Изготовление железобетонных строительных изделий и деталей
9319103: Благоустройство территории индивидуальных домовладений
9319104: Землеустроительные и мелиоративные работы
9319105: Разработка проектно - сметной документации на строительство реконструкцию жилых и нежилых строений, благоустройство индивидуальных домов и приусадебных участков
9319107: Разработка эскизов и оформление интерьеров квартир по заявкам населения
9319108: Услуги в системе инвентаризации служебных и основных строений с пристройками по установленным формам
1120111: Строительство буровых вышек
1120112: Ремонт буровых вышек
1120113: Демонтаж буровых вышек
9319130: Сборка, подвеска, монтаж и демонтаж осветительной аппаратуры
5200293: Работы, связанные с выполнением витражей ??????
9412212: Выполнение плиссировочных и гофрировочных работ   ?????
9412353: Выполнение различных видов отделочных работ
9319103: Благоустройство территории индивидуальных домовладений
9440331: Услуги газификации - ремонт газовых сетей
9440332: Услуги газификации - прокладка газовых сетей
9440333: Услуги газификации - установка газовых приборов
9440334: Услуги газификации - переоборудование газовых сетей
9440335: Услуги газификации - ремонт газовых баллонов
9440336: Услуги газификации - заправка населению газовых баллонов
9440337: Услуги газификации - доставка населению газовых баллонов
9440339: Услуги газификации - работы по газификации прочие (противокоррозийная усиленная изоляция трубопроводов и стыков трубопроводов)