'7420000': 'УСЛУГИ В ОБЛАСТИ ТЕХНИЧЕСКОЙ ДЕЯТЕЛЬНОСТИ УСЛУГИ В ОБЛАСТИ АРХИТЕКТУРЫ ИНЖЕНЕРНЫЕ УСЛУГИ В ОБЛАСТИ ГРАЖДАНСКОГО И ПРОМЫШЛЕННОГО СТРОИТЕЛЬСТВА УСЛУГИ ПО ТЕХНИЧЕСКИМ ИСПЫТАНИЯМ И АНАЛИЗУ'
'7421024': 'Инженерные услуги в области проектно - конструкторских работ, связанные с проектированием зданий'
'3313542': 'Программно - технические комплексы для автоматизации проектирования объектов строительства (зданий и сооружений)'
'9319105': 'Разработка проектно - сметной документации на строительство реконструкцию жилых и нежилых строений, благоустройство индивидуальных домов и приусадебных участков'
'7421011': 'Консультативные услуги в области архитектуры на предварительных стадиях проектирования объектов'
'7421012': 'Услуги по архитектурным проектировочным работам'
'7421014': 'Комплексные услуги по проектировочным работам и административные услуги по контрактам в области архитектуры'
'7421022': 'Инженерные услуги в области проектно - конструкторских работ, связанные с закладкой фундамента и строительных конструкций'
'7421023': 'Инженерные услуги в области проектно - конструкторских работ, связанные с электромеханическим оборудованием зданий'
'7421024': 'Инженерные услуги в области проектно - конструкторских работ, связанные с проектированием зданий'
'7421025': 'Инженерные услуги в области проектно - конструкторских работ для промышленных технологических процессов и производств'
'7421029': 'Инженерные услуги в области проектно - строительных работ прочие'
'7421051': 'Комплексные инженерные услуги для проектов транспортной инфраструктурой со сдачей "под ключ"'
'7421052': 'Комплексные инженерные услуги для проектов водоснабжения и канализации'
'7421053': 'Комплексные инженерные услуги для проектов предприятий обрабатывающей промышленности со сдачей "под ключ"'
'7421054': 'Комплексные инженерные услуги для проектов гражданского строительства со сдачей "под ключ"'
'7421059': 'Комплексные инженерные услуги для проектов со сдачей "под ключ" прочих'
'7421201': 'Планы и чертежи архитектурных объектов в виде оригиналов, выполненных от руки'
'7421202': 'Планы и чертежи инженерных объектов в виде оригиналов, выполненных от руки'
'7421203': 'Планы и чертежи промышленных объектов в виде оригиналов, выполненных от руки'
'7421204': 'Планы и чертежи коммерческих объектов в виде оригиналов, выполненных от руки'
'7421205': 'Планы топографические и чертежи объектов в виде оригиналов, выполненных от руки'
'7421209': 'Планы и чертежи объектов в виде оригиналов, выполненных от руки, прочих'
'7421221': 'Фоторепродукции планов и чертежей объектов в виде оригиналов, выполненных от руки'
'7421222': 'Фоторепродукции текстов рукописных'
'7421000': 'Консультативные и инженерные услуги в области архитектуры, гражданского и промышленного строительства'